booktime/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from main import admin

urlpatterns = [
    path('admin/', admin.main_admin.urls),
    path('office-admin/', admin.central_office_admin.urls),
    path('dispatch-admin/', admin.dispatchers_admin.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from rest_framework import routers

from main import endpoints, forms, models, views

router = routers.DefaultRouter()
router.register(r'orderlines', endpoints.PaidOrderLineViewSet)
router.register(r'orders', endpoints.PaidOrderViewSet)

urlpatterns = [
    path("address/", views.AddressListView.as_view(), name="address_list",),
    path("address/create/", views.AddressCreateView.as_view(), name="address_create",),
    path("address/<int:pk>/", views.AddressUpdateView.as_view(), name="address_update",),
    path("address/<int:pk>/delete/", views.AddressDeleteView.as_view(), name="address_delete",),
    path("contact-us/", views.ContactUsView.as_view(), name="contact_us"),
    path("about-us/", TemplateView.as_view(template_name="about_us.html"), name="about_us"),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("products/<slug:tag>/", views.ProductListView.as_view(), name="products"),
    path("product/<slug:slug>/", DetailView.as_view(model=models.Product), name="product"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html",
                                                form_class=forms.AuthenticationForm), name="login"),
    path("add_to_basket/", views.add_to_basket, name="add_to_basket",),
    path("basket/", views.manage_basket, name="basket"),
    path("order/done/", TemplateView.as_view(template_name="order_done.html"), name="checkout_done"),
    path("address-select/", views.AddressSelectionView.as_view(), name="address_select"),
    path("order-dashboard/", views.OrderView.as_view(), name="order_dashboard",),
    path("api/", include(router.urls)),
    path("customer-service/<int:order_id>/", views.room, name="cs_chat"),
]

main/models.py
import logging

from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core import exceptions
from django.core.validators import MinValueValidator
from django.db import models

logger = logging.getLogger(__name__)


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    @property
    def is_employee(self):
        return self.is_active and (
            self.is_superuser or self.is_staff and self.groups.filter(name="Employees").exists()
        )

    @property
    def is_dispatcher(self):
        return self.is_active and (
            self.is_superuser or self.is_staff and self.groups.filter(name="Dispatchers").exists()
        )


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class ProductTag(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = ProductTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


class Product(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(ProductTag, blank=True)

    objects = ActiveManager()

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(upload_to="product-thumbnails", null=True)


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1", max_length=60)
    address2 = models.CharField("Address line 2", max_length=60, blank=True)
    zip_code = models.CharField("ZIP / Postal code", max_length=12)
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=3, choices=SUPPORTED_COUNTRIES)

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.zip_code,
                self.city,
                self.country,
            ]
        )


class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = (
        (OPEN, "Open"),
        (SUBMITTED, "Submitted"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

    def create_order(self, billing_address, shipping_address):
        if not self.user:
            raise exceptions.BasketException("Cannot create order without user")

        logger.info("Creating order for basket_id=%d, shipping_address= %d, billing_address= %d",
                    self.id, shipping_address.id, billing_address.id)
        order_data = {
            "user": self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_zip_code": shipping_address.zip_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
        }

        order = Order.objects.create(**order_data)
        c = 0
        for line in self.basketline_set.all():
            for item in range(line.quantity):
                order_line_data = {
                    "order": order,
                    "product": line.product,
                }
                order_line = OrderLine.objects.create(**order_line_data)
                c += 1
        logger.info("Created order with id=%d and lines_count=%d", order.id, c)

        self.status = Basket.SUBMITTED
        self.save()
        return order


class BasketLine(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])


class Order(models.Model):
    NEW = 10
    PAID = 20
    DONE = 30
    STATUSES = ((NEW, 'New'), (PAID, 'Paid'), (DONE, "Done"))

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUSES, default=NEW)

    billing_name = models.CharField(max_length=60)
    billing_address1 = models.CharField(max_length=60)
    billing_address2 = models.CharField(max_length=60, blank=True)
    billing_zip_code = models.CharField(max_length=12)
    billing_city = models.CharField(max_length=60)
    billing_country = models.CharField(max_length=3)

    shipping_name = models.CharField(max_length=60)
    shipping_address1 = models.CharField(max_length=60)
    shipping_address2 = models.CharField(max_length=60, blank=True)
    shipping_zip_code = models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)

    date_updated = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)


class OrderLine(models.Model):
    NEW = 10
    PROCESSING = 20
    SENT = 30
    CANCELLED = 40
    STATUSES = (
        (NEW, 'New'),
        (PROCESSING, 'Processing'),
        (SENT, 'Sent'),
        (CANCELLED, 'Cancelled'),
    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='lines')
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUSES, default=NEW)

main/views.py
import logging

import django_filters
from django import forms as django_forms
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import models as django_models
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, ListView
from django.views.generic.edit import (CreateView, DeleteView, FormView,
                                       UpdateView)
from django_filters.views import FilterView

from main import forms, models

logger = logging.getLogger(__name__)


def home(request):
    return render(request, "home.html", {})


class ContactUsView(FormView):
    template_name = "contact_form.html"
    form_class = forms.ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)


class ProductListView(ListView):
    template_name = "main/product_list.html"
    paginate_by = 4

    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None
        if tag != "all":
            self.tag = get_object_or_404(models.ProductTag, slug=tag)

        if self.tag:
            products = models.Product.objects.active().filter(tag=self.tag)
        else:
            products = models.Product.objects.active()
        return products.order_by("name")


class SignupView(FormView):
    template_name = "signup.html"
    form_class = forms.UserCreationForm

    def get_success_url(self):
        redirect_to = self.request.GET.get("next", "/")
        return redirect_to

    def form_valid(self, form):
        response = super().form_valid(form)
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        logger.info("New signup for email=%s through SignupView", email)
        user = authenticate(email=email, password=raw_password)
        login(self.request, user)

        form.send_mail()

        messages.info(self.request, "You signed up successfully.")
        return response


class AddressListView(LoginRequiredMixin, ListView):
    model = models.Address

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressCreateView(LoginRequiredMixin, CreateView):
    model = models.Address
    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country",
    ]
    success_url = reverse_lazy("address_list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Address
    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country",
    ]
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Address
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


def add_to_basket(request):
    product = get_object_or_404(models.Product, pk=request.GET.get("product_id"))
    basket = request.basket
    if not request.basket:
        if request.user.is_authenticated:
            user = request.user
        else:
            user = None
        basket = models.Basket.objects.create(user=user)
        request.session["basket_id"] = basket.id
    basketline, created = models.BasketLine.objects.get_or_create(basket=basket,
                                                                  product=product)
    if not created:
        basketline.quantity += 1
        basketline.save()
    return HttpResponseRedirect(reverse("product", args=(product.slug,)))


def manage_basket(request):
    if not request.basket:
        return render(request, "basket.html", {"formset": None})

    if request.method == "POST":
        formset = forms.BasketLineFormSet(request.POST, instance=request.basket)
        if formset.is_valid():
            formset.save()

    else:
        formset = forms.BasketLineFormSet(instance=request.basket)

    if request.basket.is_empty():
        return render(request, "basket.html", {"formset": None})

    return render(request, "basket.html", {"formset": formset})


class AddressSelectionView(LoginRequiredMixin, FormView):
    template_name = 'address_select.html'
    form_class = forms.AddressSelectionForm
    success_url = reverse_lazy('checkout_done')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        del self.request.session['basket_id']
        basket = self.request.basket
        basket.create_order(form.cleaned_data['billing_address'],
                            form.cleaned_data['shipping_address'])
        return super().form_valid(form)


class DateInput(django_forms.DateInput):
    input_type = 'date'


class OrderFilter(django_filters.FilterSet):
    class Meta:
        model = models.Order
        fields = {
            'user__email': ['icontains'],
            'status': ['exact'],
            'date_updated': ['gt', 'lt'],
            'date_added': ['gt', 'lt'],
        }
        filter_overrides = {
            django_models.DateTimeField: {
                'filter_class': django_filters.DateFilter,
                'extra': lambda f: {'widget': DateInput}
            }
        }


class OrderView(UserPassesTestMixin, FilterView):
    filterset_class = OrderFilter
    login_url = reverse_lazy("login")

    def test_func(self):
        return self.request.user.is_staff is True


def room(request, order_id):
    context = {"room_name_json": str(order_id)}
    return render(request, "chat_room.html", context)

main/templates/main/address_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h2>Delete address</h2>
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete it?</p>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

main/templates/main/address_form.html
{% extends "base.html" %}

{% block content %}
<h2>Add new address</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

main/templates/main/address_list.html
{% extends "base.html" %}

{% block content %}
<h1>List of your addresses:</h1>
{% for address in object_list %}
<p>
    {{ address.name }}<br>
    {{ address.address1 }}<br>
    {{ address.address2 }}<br>
    {{ address.city }}<br>
    {{ address.country }}<br>
</p>
<p>
    <a href="{% url 'address_update' address.id %}">Update address</a>
</p>
<p>
    <a href="{% url 'address_delete' address.id %}">Delete address</a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<p>
    <a href="{% url 'address_create' %}">Add new address</a>
</p>
{% endblock content%}

main/templates/main/address_update.html
{% extends "base.html" %}

{% block content %}
<h2>Add a new address</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}

main/templates/main/order_filter.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block content %}
<h2>Order dashboard</h2>
<form method="GET">
    {{ filter.form.as_p }}
    <input type="submit" />
</form>
<p>{% render_table filter.qs %}</p>
{% endblock content %}

main/templates/main/product_detail.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% block content %}
<h1>Products</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <td>{{ object.name }}</td>
    </tr>
    <tr>
        <th>Cover images</th>
        <td>
            <div id="imagebox">
                Loading...
            </div>
        </td>
    </tr>
    <tr>
        <th>Price</th>
        <td>{{ object.price }}</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>{{ object.description|linebreaks }}</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>{{ object.tags.all|join:","|default:"No tags available" }}</td>
    </tr>
    <tr>
        <th>In stock</th>
        <td>{{ object.in_stock|yesno|capfirst }}</td>
    </tr>
    <tr>
        <th>Updated</th>
        <td>{{ object.date_updated|date:"F Y" }}</td>
    </tr>
</table>
<a href="{% url 'add_to_basket' %}?product_id={{ object.id }}">Add to basket</a>
{% endblock content %}

{% block js %}
{% render_bundle 'imageswitcher' 'js' %}
<script>
    document.addEventListener("DOMContentLoaded",
        function (event) {
            var images = [
                {% for image in object.productimage_set.all %}
            {
            "image": "{{ image.image.url }}",
            "thumbnail": "{{ image.thumbnail.url }}"
        },
        {% endfor %}
        ]
        ReactDOM.render(
            React.createElement(
                ImageBox, {
                images: images,
                imageStart: images[0]
            }
            ),
            document.getElementById('imagebox')
        );
    }
    );
</script>
{% endblock %}

main/templates/main/product_list.html
{% extends "base.html" %}

{% block content %}
<h1>Products</h1>
{% for product in page_obj %}
<p>{{ product.name }}</p>
<p>
    <a href="{% url 'product' product.slug %}">See it here</a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}

<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
        </li>
        {% endif %}
        {% for pagenum in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == pagenum %}active{% endif %}">
            <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock content %}