booktime/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from main import admin

urlpatterns = [
    path('admin/', admin.main_admin.urls),
    path('office-admin/', admin.central_office_admin.urls),
    path('dispatch-admin/', admin.dispatchers_admin.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from rest_framework import routers

from main import endpoints, forms, models, views

router = routers.DefaultRouter()
router.register(r'orderlines', endpoints.PaidOrderLineViewSet)
router.register(r'orders', endpoints.PaidOrderViewSet)

urlpatterns = [
    path("address/", views.AddressListView.as_view(), name="address_list",),
    path("address/create/", views.AddressCreateView.as_view(), name="address_create",),
    path("address/<int:pk>/", views.AddressUpdateView.as_view(), name="address_update",),
    path("address/<int:pk>/delete/", views.AddressDeleteView.as_view(), name="address_delete",),
    path("contact-us/", views.ContactUsView.as_view(), name="contact_us"),
    path("about-us/", TemplateView.as_view(template_name="about_us.html"), name="about_us"),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("products/<slug:tag>/", views.ProductListView.as_view(), name="products"),
    path("product/<slug:slug>/", DetailView.as_view(model=models.Product), name="product"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html",
                                                form_class=forms.AuthenticationForm), name="login"),
    path("add_to_basket/", views.add_to_basket, name="add_to_basket",),
    path("basket/", views.manage_basket, name="basket"),
    path("order/done/", TemplateView.as_view(template_name="order_done.html"), name="checkout_done"),
    path("address-select/", views.AddressSelectionView.as_view(), name="address_select"),
    path("order-dashboard/", views.OrderView.as_view(), name="order_dashboard",),
    path("api/", include(router.urls)),
    path("customer-service/<int:order_id>/", views.room, name="cs_chat"),
]

main/models.py
import logging

from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core import exceptions
from django.core.validators import MinValueValidator
from django.db import models

logger = logging.getLogger(__name__)


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    @property
    def is_employee(self):
        return self.is_active and (
            self.is_superuser or self.is_staff and self.groups.filter(name="Employees").exists()
        )

    @property
    def is_dispatcher(self):
        return self.is_active and (
            self.is_superuser or self.is_staff and self.groups.filter(name="Dispatchers").exists()
        )


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class ProductTag(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = ProductTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


class Product(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(ProductTag, blank=True)

    objects = ActiveManager()

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(upload_to="product-thumbnails", null=True)


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1", max_length=60)
    address2 = models.CharField("Address line 2", max_length=60, blank=True)
    zip_code = models.CharField("ZIP / Postal code", max_length=12)
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=3, choices=SUPPORTED_COUNTRIES)

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.zip_code,
                self.city,
                self.country,
            ]
        )


class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = (
        (OPEN, "Open"),
        (SUBMITTED, "Submitted"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

    def create_order(self, billing_address, shipping_address):
        if not self.user:
            raise exceptions.BasketException("Cannot create order without user")

        logger.info("Creating order for basket_id=%d, shipping_address= %d, billing_address= %d",
                    self.id, shipping_address.id, billing_address.id)
        order_data = {
            "user": self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_zip_code": shipping_address.zip_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
        }

        order = Order.objects.create(**order_data)
        c = 0
        for line in self.basketline_set.all():
            for item in range(line.quantity):
                order_line_data = {
                    "order": order,
                    "product": line.product,
                }
                order_line = OrderLine.objects.create(**order_line_data)
                c += 1
        logger.info("Created order with id=%d and lines_count=%d", order.id, c)

        self.status = Basket.SUBMITTED
        self.save()
        return order


class BasketLine(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])


class Order(models.Model):
    NEW = 10
    PAID = 20
    DONE = 30
    STATUSES = ((NEW, 'New'), (PAID, 'Paid'), (DONE, "Done"))

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUSES, default=NEW)

    billing_name = models.CharField(max_length=60)
    billing_address1 = models.CharField(max_length=60)
    billing_address2 = models.CharField(max_length=60, blank=True)
    billing_zip_code = models.CharField(max_length=12)
    billing_city = models.CharField(max_length=60)
    billing_country = models.CharField(max_length=3)

    shipping_name = models.CharField(max_length=60)
    shipping_address1 = models.CharField(max_length=60)
    shipping_address2 = models.CharField(max_length=60, blank=True)
    shipping_zip_code = models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)

    date_updated = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)


class OrderLine(models.Model):
    NEW = 10
    PROCESSING = 20
    SENT = 30
    CANCELLED = 40
    STATUSES = (
        (NEW, 'New'),
        (PROCESSING, 'Processing'),
        (SENT, 'Sent'),
        (CANCELLED, 'Cancelled'),
    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='lines')
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUSES, default=NEW)

main/forms.py
import logging

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import \
    UserCreationForm as DjangoUserCreationForm
from django.contrib.auth.forms import UsernameField
from django.core.mail import send_mail
from django.forms import inlineformset_factory

from . import models, widgets

logger = logging.getLogger(__name__)


class UserCreationForm(DjangoUserCreationForm):

    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info("Sending signup email for email=%s", self.cleaned_data["email"],)
        message = "Welcome{}".format(self.cleaned_data["email"])
        send_mail(
            "Welcome to BookTime",
            message,
            "site@booktime.domain",
            [self.cleaned_data["email"]],
            fail_silently=True,
        )


class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(self.cleaned_data['name'], self.cleaned_data['message'])
        send_mail("Site message", message, "site@booktime.domain",
                  ["customerservice@booktime.domain"], fail_silently=False)


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user = authenticate(self.request, email=email, password=password)
            if self.user is None:
                raise forms.ValidationError("Invalid email/password combination.")
            logger.info("Authentication successful for email=%s", email)
        return self.cleaned_data

    def get_user(self):
        return self.user


BasketLineFormSet = inlineformset_factory(models.Basket,
                                          models.BasketLine,
                                          fields=("quantity",),
                                          extra=0,
                                          widgets={"quantity": widgets.PlusMinusNumberInput()}
                                          )


class AddressSelectionForm(forms.Form):
    billing_address = forms.ModelChoiceField(queryset=None)
    shipping_address = forms.ModelChoiceField(queryset=None)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = models.Address.objects.filter(user=user)
        self.fields['billing_address'].queryset = queryset
        self.fields['shipping_address'].queryset = queryset

main/templates/about_us.html
{% extends "base.html" %}

{% block content %}
<h2>About us</h2>
<p>BookTime is a company that sells books online.</p>
{% endblock content %}

main/templates/address_select.html
{% extends 'base.html' %}

{% block content %}
<h2>Select the billing/shipping addresses</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-primary" href="{% url 'address_create' %}">Add a new one</a>
</form>
{% endblock content %}

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to- fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>BookTime</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">BookTime</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse         navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item {% if request.path == '/products/' %}active{% endif %}">
                    <a class="nav-link" href="/products/all">Products</a>
                </li>
                <li class="nav-item {% if request.path == '/basket/' %}active{% endif %}">
                    <a class="nav-link" href="/basket/">Basket</a>
                </li>
                <li class="nav-item {% if request.path == '/about-us/' %}active{% endif %}">
                    <a class="nav-link" href="/about-us/">About</a>
                </li>
                <li class="nav-item {% if request.path == '/contact-us' %}active{% endif %}">
                    <a class="nav-link" href="/contact-us/">Contact</a>
                </li>
                <li class="nav-item {% if request.path == '/login' %}active{% endif %}">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
                <li class="nav-item {% if request.path == '/sign-up' %}active{% endif %}">
                    <a class="nav-link" href="/signup/">Sign Up</a>
                </li>
            </ul>
        </div>
    </nav>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% if request.basket %}
    <div>
        {{ request.basket.count }}
        items in basket
    </div>
    {% endif %}
    {% block content %}
    {% endblock content %}
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    {% block js %}
    {% endblock js %}
</body>

</html>

main/templates/basket.html
{% extends "base.html" %}

{% block content %}
<h2>Basket</h2>
{% if formset %}
<p>You adjust the quantities below.</p>
<form method="POST">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
    <p>
        {{ form.instance.product.name }}
        {{ form }}
    </p>
    {% endfor %}
    <button type="submit" class="btn btn-default">Update basket</button>
    {% if user.is_authenticated %}
    <a href="{% url 'address_select' %}" class="btn btn-primary">Place order</a>
    {% else %}
    <a href="{% url 'signup' %}?next={% url 'address_select' %}" class="btn btn-primary">Signup</a>
    <a href="{% url 'login' %}?next={% url 'address_select' %}" class="btn btn-primary">Login</a>
    {% endif %}
</form>
{% else %}
<p>You have no items in the basket</p>
{% endif %}
{% endblock content %}

{% block js %}
{% if formset %}
{{ formset.media }}
{% endif %}
{% endblock js %}

main/templates/chat_room.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Chat Room</title>
    <script src="{% static 'js/reconnecting-websocket.min.js' %}" charset="utf-8"></script>
</head>

<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100" /><br>
    <input id="chat-message-submit" type="button" value="Send" />
</body>
<script>
    var roomName = {{ room_name_json }};
    var chatSocket = new ReconnectingWebSocket(
        'ws://' + window.location.host + '/ws/customer-service/' + 'roomName' + '/'
    );
    chatSocket.onmessage = function (e) {
        var data = JSON.parse(e.data);
        var username = data['username'];
        
        if (data['type'] == "chat_join") {
            message = (username + ' joined\n ');
        }
        else if (data['type'] == "chat_leave") {
            message = (username + ' left\n ');
        }
        else {
            message = (username + ': ' + data['message'] + '\n');
        }
        document.querySelector('#chat-log').value += message;
    };
    
    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) { // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };
    

    document.querySelector('#chat-message-submit').onclick() = function (e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        
        chatSocket.send(
            JSON.stringify({'type': 'message', 'message': message});
        );
        messageInputDom.value = '';
    };
    
    setInterval(function () {
        chatSocket.send(JSON.stringify({'type': 'heartbeat'}));
    }, 10000);
</script>
</html>

main/templates/contact_form.html
{% extends "base.html" %}

{% block content %}
<h2>Contact us</h2>
<p>Please fill the form below to contact us</p>
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.name.label_tag }}
        <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_name" name="name"
            placeholder="Your name" value="{{ form.name.value|default:'' }}">
        {% if form.name.errors %}
        <div class="invalid-feedback">{{ form.name.errors }}</div>
        {% endif %}
    </div>

    <div class="form-group">
        {{ form.message.label_tag }}
        <textarea class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_message" name="message"
            rows="3">
            {{ form.message.value|default:'' }}
        </textarea>
        {% if form.message.errors %}
        <div class="invalid-feedback">{{ form.message.errors }}</div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

main/templates/home.html
{% extends "base.html" %}

{% block content %}
<h2>Home</h2>
<p>this will be the content of home</p>
{% endblock content %}

main/templates/invoice.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Invoice</title>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h1>BookTime</h1>
                <h2>Invoice</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                Invoice number BT{{ order.id }}<br>
                Date: {{ order.date_added|date }}
            </div>
            <div class="col-4">
                {{ order.billing_name }}<br>
                {{ order.billing_address1 }}<br>
                {{ order.billing_address2 }}<br>
                {{ order.billing_zip_code }}<br>
                {{ order.billing_city }}<br>
                {{ order.billing_country }}<br>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table" style="width: 95%; margin: 50px 0px 50px 0px;">
                    <tr>
                        <th>Product name</th>
                        <th>Price</th>
                    </tr>
                    {% for line in order.lines.all %}
                    <tr>
                        <td>{{ line.product.name }}</td>
                        <td>{{ line.product.price }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p>Please pay within 30 days</p>
                <p>BookTime inc.</p>
            </div>
        </div>
    </div>
</body>

</html>

main/templates/login.html
{% extends "base.html" %}

{% block content %}
<h2>Login</h2>
<p>Please fill the form below.</p>
<form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% include "includes/field.html" with field=form.email %}
    {% include "includes/field.html" with field=form.password %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

main/templates/order_done.html
{% extends 'base.html' %}
{% block content %}
<p>Thanks for your order</p>
{% endblock content %}

main/templates/signup.html
{% extends "base.html" %}

{% block content %}
<h2>Sign Up</h2>
<p>Please fill in the form below.</p>
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.email.label_tag }}
        <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
            name="email" placeholder="Your email" value="{{ form.email.value|default:'' }}">
        {% if form.email.errors %}
        <div class="invalid-feedback">
            {{ form.email.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password1.label_tag }}
        <input type="password" class="form-control {% if form.password1.errors %}is-invalid{% endif %}"
            id="id_password1" name="password1" value="{{ form.password1.value|default:'' }}">
        {% if form.password1.errors %}
        <div class="invalid-feedback">
            {{ form.password1.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password2.label_tag }}
        <input type="password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}"
            id="id_password2" name="password2" value="{{ form.password2.value|default:'' }}">
        {% if form.password2.errors %}
        <div class="invalid-feedback">
            {{ form.password2.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}